name: Main


on:
  workflow_dispatch:
  schedule:
    - cron: "10 12 * * *"
  
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install OS deps for headless Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libpango-1.0-0 \
            libasound2t64

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run monitor
        # point pyppeteer at the system Chrome rather than downloading its own
        env:
          PYTHONPATH: ./src   
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
          SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
          SMTP_SERVER:   ${{ secrets.SMTP_SERVER }}
          SMTP_PORT:     ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python -m src.main
